import { Gender, HairstyleOption, HairLength, HairColor } from './types';

export const HAIRSTYLES: HairstyleOption[] = [
  // --- FEMALE STYLES (30) ---
  
  // Long
  {
    id: 'f1',
    name: 'Bohemian Blonde Waves',
    name_zh: '波西米亚金发波浪',
    name_vi: 'Tóc Xoăn Sóng Vàng Bohemian',
    name_th: 'ผมลอนทองสไตล์โบฮีเมียน',
    description: 'Long, loose beachy waves',
    description_zh: '长发，宽松的沙滩波浪卷',
    description_vi: 'Tóc dài, uốn sóng lơi kiểu bãi biển',
    description_th: 'ผมยาวลอนคลายสไตล์ชายหาด',
    prompt: 'change the hairstyle to long, loose bohemian beach waves, platinum blonde color',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BLONDE
  },
  {
    id: 'f2',
    name: 'Sleek Straight Black',
    name_zh: '柔顺黑长直',
    name_vi: 'Tóc Đen Dài Suôn Mượt',
    name_th: 'ผมดำยาวตรงสลวย',
    description: 'Ultra-long, shiny straight hair',
    description_zh: '超长，光泽顺滑的直发',
    description_vi: 'Tóc siêu dài, thẳng mượt và bóng',
    description_th: 'ผมยาวตรงเงางามเป็นพิเศษ',
    prompt: 'change the hairstyle to ultra-long, silky straight jet black hair',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BLACK
  },
  {
    id: 'f3',
    name: 'Copper Red Layers',
    name_zh: '铜红色层次长发',
    name_vi: 'Tóc Tỉa Layer Màu Đỏ Đồng',
    name_th: 'ผมยาวสไลด์เลเยอร์สีแดงทองแดง',
    description: 'Long layered cut with face framing',
    description_zh: '长发层次剪裁，修饰脸型',
    description_vi: 'Tóc tỉa layer dài ôm lấy khuôn mặt',
    description_th: 'ผมยาวสไลด์ไล่ระดับกรอบหน้า',
    prompt: 'change the hairstyle to long layered hair with face-framing pieces, vibrant copper red color',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.RED
  },
  {
    id: 'f4',
    name: 'Chocolate Brown Braids',
    name_zh: '巧克力棕编发',
    name_vi: 'Tóc Tết Màu Nâu Chocolate',
    name_th: 'ผมถักเปียสีน้ำตาลช็อกโกแลต',
    description: 'Long intricate box braids',
    description_zh: '长款精致雷鬼脏辫/盒状编发',
    description_vi: 'Tóc tết box braids dài tinh tế',
    description_th: 'ผมถักเปียยาวประณีต',
    prompt: 'change the hairstyle to long, neat box braids, rich chocolate brown color',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BROWN
  },
  {
    id: 'f5',
    name: 'Silver Ponytail',
    name_zh: '银色高马尾',
    name_vi: 'Tóc Đuôi Ngựa Màu Bạc',
    name_th: 'ผมหางม้าสีเงิน',
    description: 'High sleek ponytail',
    description_zh: '高耸利落的马尾辫',
    description_vi: 'Tóc buộc đuôi ngựa cao mượt mà',
    description_th: 'ผมรวบหางม้าสูงเรียบหรู',
    prompt: 'change the hairstyle to a high, sleek ponytail with silver grey hair',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.SILVER
  },

  // Medium
  {
    id: 'f6',
    name: 'Classic Blonde Bob',
    name_zh: '经典金发波波头',
    name_vi: 'Tóc Bob Vàng Cổ Điển',
    name_th: 'ผมบอบสีบลอนด์คลาสสิก',
    description: 'Chin-length classic bob cut',
    description_zh: '齐下巴长度的经典波波头',
    description_vi: 'Kiểu tóc bob cổ điển dài ngang cằm',
    description_th: 'ผมบอบสั้นระดับคาง',
    prompt: 'change the hairstyle to a classic chin-length bob cut, honey blonde color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLONDE
  },
  {
    id: 'f7',
    name: 'Textured Brown Lob',
    name_zh: '纹理感棕色长波波',
    name_vi: 'Tóc Lob Nâu Có Kết Cấu',
    name_th: 'ผมบอบยาวสีน้ำตาลมีเท็กซ์เจอร์',
    description: 'Shoulder-length long bob (Lob)',
    description_zh: '齐肩长度的长波波头(Lob)',
    description_vi: 'Tóc bob dài (Lob) ngang vai',
    description_th: 'ผมบอบยาวประบ่า (Lob)',
    prompt: 'change the hairstyle to a textured shoulder-length long bob (lob), dark brown color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'f8',
    name: 'Shaggy Black Wolf Cut',
    name_zh: '黑色鲻鱼狼尾剪',
    name_vi: 'Tóc Wolf Cut Màu Đen Phóng Khoáng',
    name_th: 'ทรงผม Wolf Cut สีดำเซอร์ๆ',
    description: 'Trendy medium layered shag',
    description_zh: '时髦的中长碎发层次剪裁',
    description_vi: 'Kiểu tóc shag tỉa layer thời thượng',
    description_th: 'ทรงผมซอยสไลด์สไตล์ยอดฮิต',
    prompt: 'change the hairstyle to a trendy medium-length wolf cut with bangs, black color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'f9',
    name: 'Curly Red Shoulder',
    name_zh: '齐肩红色卷发',
    name_vi: 'Tóc Xoăn Đỏ Ngang Vai',
    name_th: 'ผมลอนแดงประบ่า',
    description: 'Voluminous natural curls',
    description_zh: '蓬松自然的卷发',
    description_vi: 'Tóc xoăn tự nhiên bồng bềnh',
    description_th: 'ผมลอนธรรมชาติหนานุ่ม',
    prompt: 'change the hairstyle to voluminous shoulder-length natural curls, deep red color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.RED
  },
  {
    id: 'f10',
    name: 'Pastel Pink Mullet',
    name_zh: '粉色狼尾',
    name_vi: 'Tóc Mullet Hồng Pastel',
    name_th: 'ทรงมัลเล็ตสีชมพูพาสเทล',
    description: 'Modern feminine mullet',
    description_zh: '现代女性化狼尾发型',
    description_vi: 'Kiểu tóc mullet nữ tính hiện đại',
    description_th: 'ทรงมัลเล็ตหญิงทันสมัย',
    prompt: 'change the hairstyle to a modern feminine mullet style, pastel pink color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.COLOR
  },

  // Short
  {
    id: 'f11',
    name: 'Platinum Pixie',
    name_zh: '白金精灵短发',
    name_vi: 'Tóc Pixie Bạch Kim',
    name_th: 'ทรงพิกซี่สีบลอนด์แพลตตินัม',
    description: 'Very short chic pixie cut',
    description_zh: '超短又时尚的精灵短发',
    description_vi: 'Kiểu tóc pixie ngắn sành điệu',
    description_th: 'ทรงผมสั้นกุดสุดชิค',
    prompt: 'change the hairstyle to a very short, chic pixie cut, platinum blonde color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.BLONDE
  },
  {
    id: 'f12',
    name: 'Short Black French Bob',
    name_zh: '法式黑色短波波',
    name_vi: 'Tóc Bob Pháp Ngắn Màu Đen',
    name_th: 'ผมบอบฝรั่งเศสสั้นสีดำ',
    description: 'Ear-length bob with bangs',
    description_zh: '齐耳长度带刘海的波波头',
    description_vi: 'Tóc bob ngang tai có mái',
    description_th: 'ผมบอบสั้นระดับหูพร้อมหน้าม้า',
    prompt: 'change the hairstyle to a very short French bob with micro bangs, black color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'f13',
    name: 'Brown Bixie',
    name_zh: '棕色 Bixie 发型',
    name_vi: 'Tóc Bixie Màu Nâu',
    name_th: 'ทรง Bixie สีน้ำตาล',
    description: 'Bob-Pixie hybrid',
    description_zh: '波波头与精灵短发的结合体',
    description_vi: 'Sự kết hợp giữa Bob và Pixie',
    description_th: 'ลูกผสมระหว่างบอบและพิกซี่',
    prompt: 'change the hairstyle to a "bixie" cut (pixie bob hybrid), chestnut brown color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.BROWN
  },
  {
    id: 'f14',
    name: 'Icy Silver Undercut',
    name_zh: '冰银色铲青',
    name_vi: 'Undercut Màu Bạc Băng Giá',
    name_th: 'อันเดอร์คัทสีเงินไอซ์ซี่',
    description: 'Edgy undercut with long top',
    description_zh: '前卫的铲青，顶部留长',
    description_vi: 'Kiểu undercut cá tính với phần đỉnh dài',
    description_th: 'ทรงไถข้างสุดเท่พร้อมผมด้านบนยาว',
    prompt: 'change the hairstyle to an edgy undercut with swept back top, icy silver color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.SILVER
  },
  {
    id: 'f15',
    name: 'Neon Blue Buzz',
    name_zh: '霓虹蓝寸头',
    name_vi: 'Đầu Đinh Màu Xanh Neon',
    name_th: 'ทรงสกินเฮดสีนีออนบลู',
    description: 'Buzz cut with fashion color',
    description_zh: '染成时尚色的寸头',
    description_vi: 'Kiểu đầu đinh với màu thời trang',
    description_th: 'ทรงสกินเฮดทำสีแฟชั่น',
    prompt: 'change the hairstyle to a military buzz cut dyed electric neon blue',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.COLOR
  },
  {
    id: 'f16',
    name: 'Hime Cut',
    name_zh: '公主切',
    name_vi: 'Kiểu Tóc Hime',
    name_th: 'ทรงผมฮิเมะคัท',
    description: 'Straight hair with cheek-length sidelocks',
    description_zh: '直发，脸颊两侧有平剪的发束',
    description_vi: 'Tóc thẳng với phần tóc mai cắt ngắn ngang má',
    description_th: 'ผมตรงพร้อมปอยผมข้างแก้มตัดตรง',
    prompt: 'change the hairstyle to a traditional Hime cut with blunt cheek-length sidelocks, black color',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BLACK
  },
  {
    id: 'f17',
    name: 'Space Buns',
    name_zh: '双丸子头',
    name_vi: 'Tóc Búi Hai Bên',
    name_th: 'ผมมัดจุกคู่ (Space Buns)',
    description: 'Two cute buns on top',
    description_zh: '头顶两侧可爱的丸子头',
    description_vi: 'Hai búi tóc dễ thương trên đỉnh đầu',
    description_th: 'มัดจุกกลมสองข้างบนศีรษะสุดน่ารัก',
    prompt: 'change the hairstyle to cute double space buns on top of the head, dark brown color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'f18',
    name: 'Finger Waves',
    name_zh: '复古手推波纹',
    name_vi: 'Tóc Uốn Sóng Cổ Điển',
    name_th: 'ผมดัดลอนเปียกวินเทจ',
    description: '1920s vintage style',
    description_zh: '1920年代复古风格波纹',
    description_vi: 'Phong cách cổ điển thập niên 1920',
    description_th: 'สไตล์วินเทจยุค 1920',
    prompt: 'change the hairstyle to 1920s vintage finger waves, blonde color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.BLONDE
  },
  {
    id: 'f19',
    name: 'Natural Afro',
    name_zh: '自然爆炸头',
    name_vi: 'Tóc Xù Afro Tự Nhiên',
    name_th: 'ทรงผมแอฟโฟรธรรมชาติ',
    description: 'Voluminous round afro',
    description_zh: '蓬松圆润的爆炸头',
    description_vi: 'Tóc xù tròn đầy đặn',
    description_th: 'ผมฟูทรงกลมมีวอลลุ่ม',
    prompt: 'change the hairstyle to a large, voluminous natural afro, black color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'f20',
    name: 'Cornrow Braids',
    name_zh: '贴头辫',
    name_vi: 'Tóc Tết Sát Da Đầu',
    name_th: 'ผมถักเปียติดหนังศีรษะ (Cornrows)',
    description: 'Tight braids close to scalp',
    description_zh: '紧贴头皮的编发',
    description_vi: 'Tết tóc chặt sát da đầu',
    description_th: 'ถักเปียแน่นติดหนังศีรษะ',
    prompt: 'change the hairstyle to intricate cornrow braids, black color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'f21',
    name: 'Rainbow Layers',
    name_zh: '彩虹层次长发',
    name_vi: 'Tóc Tỉa Layer Cầu Vồng',
    name_th: 'ผมยาวสไลด์สีรุ้ง',
    description: 'Multicolor vivid dye',
    description_zh: '多色鲜艳的染发',
    description_vi: 'Nhuộm nhiều màu rực rỡ',
    description_th: 'ย้อมสีรุ้งสดใส',
    prompt: 'change the hairstyle to long layered hair dyed in vivid rainbow colors',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.COLOR
  },
  {
    id: 'f22',
    name: 'Split Dye',
    name_zh: '阴阳染',
    name_vi: 'Nhuộm Hai Màu Đối Lập',
    name_th: 'ย้อมผมสองสี (Split Dye)',
    description: 'Half black half white',
    description_zh: '一半黑一半白',
    description_vi: 'Một nửa đen một nửa trắng',
    description_th: 'ครึ่งดำครึ่งขาว',
    prompt: 'change the hairstyle to split dye hair, half black and half platinum blonde',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.COLOR
  },
  {
    id: 'f23',
    name: 'Curtain Bangs Layers',
    name_zh: '八字刘海层次感',
    name_vi: 'Tóc Mái Bay Tỉa Layer',
    name_th: 'ผมสไลด์พร้อมหน้าม้าสไลด์ข้าง',
    description: 'Soft flowing layers',
    description_zh: '柔和流动的层次感',
    description_vi: 'Các lớp tóc mềm mại',
    description_th: 'เลเยอร์นุ่มนวลพลิ้วไหว',
    prompt: 'change the hairstyle to long hair with curtain bangs and soft layers, chestnut brown',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BROWN
  },
  {
    id: 'f24',
    name: 'Asymmetrical Bob',
    name_zh: '不对称波波头',
    name_vi: 'Tóc Bob Bất Đối Xứng',
    name_th: 'ผมบอบเท (ไม่สมมาตร)',
    description: 'One side longer than other',
    description_zh: '一侧比另一侧长',
    description_vi: 'Một bên dài hơn bên kia',
    description_th: 'ข้างหนึ่งยาวกว่าอีกข้าง',
    prompt: 'change the hairstyle to a sharp asymmetrical bob, one side longer, black hair',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'f25',
    name: 'Rose Gold Waves',
    name_zh: '玫瑰金波浪',
    name_vi: 'Tóc Xoăn Sóng Màu Vàng Hồng',
    name_th: 'ผมลอนสีโรสโกลด์',
    description: 'Trendy metallic pink',
    description_zh: '时尚的金属粉色',
    description_vi: 'Màu hồng ánh kim thời thượng',
    description_th: 'สีชมพูเมทัลลิกยอดฮิต',
    prompt: 'change the hairstyle to medium wavy hair, metallic rose gold color',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.RED
  },
  {
    id: 'f26',
    name: 'Sleek Wet Look',
    name_zh: '湿发造型',
    name_vi: 'Tóc Vuốt Gel Ướt Át',
    name_th: 'ทรงผมเปียก (Wet Look)',
    description: 'High fashion gelled back',
    description_zh: '高级时尚的后梳湿发',
    description_vi: 'Vuốt ngược phong cách thời trang cao cấp',
    description_th: 'หวีเสยเรียบสไตล์ไฮแฟชั่น',
    prompt: 'change the hairstyle to a sleek combed-back wet look style, dark brown',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'f27',
    name: 'Bubble Braids',
    name_zh: '灯笼辫',
    name_vi: 'Tóc Tết Bong Bóng',
    name_th: 'ผมเปียบอลลูน (Bubble Braids)',
    description: 'Playful tied ponytails',
    description_zh: '俏皮的分节马尾辫',
    description_vi: 'Tóc đuôi ngựa buộc từng đoạn vui tươi',
    description_th: 'มัดหางม้าเป็นข้อๆ สุดเก๋',
    prompt: 'change the hairstyle to long pigtails with bubble braid style, blonde hair',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BLONDE
  },
  {
    id: 'f28',
    name: 'Top Knot Bun',
    name_zh: '高丸子头',
    name_vi: 'Búi Tóc Củ Tỏi Cao',
    name_th: 'มัดดังโงะสูง',
    description: 'Casual high bun',
    description_zh: '随性的高耸丸子头',
    description_vi: 'Búi cao tự nhiên',
    description_th: 'มัดจุกสูงแบบสบายๆ',
    prompt: 'change the hairstyle to a messy top knot bun, light brown hair',
    gender: Gender.FEMALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'f29',
    name: 'Side Swept Hollywood',
    name_zh: '好莱坞侧分大波浪',
    name_vi: 'Tóc Xoăn Lệch Hollywood',
    name_th: 'ผมลอนเบี่ยงข้างสไตล์ฮอลลีวูด',
    description: 'Glamorous red carpet look',
    description_zh: '迷人的红毯造型',
    description_vi: 'Vẻ đẹp quyến rũ thảm đỏ',
    description_th: 'ลุคพรมแดงสุดหรู',
    prompt: 'change the hairstyle to glamorous old Hollywood side-swept waves, blonde',
    gender: Gender.FEMALE,
    length: HairLength.LONG,
    color: HairColor.BLONDE
  },
  {
    id: 'f30',
    name: 'Lavender Grey Bob',
    name_zh: '薰衣草灰波波头',
    name_vi: 'Tóc Bob Màu Xám Tím',
    name_th: 'ผมบอบสีเทาม่วงลาเวนเดอร์',
    description: 'Soft purple-grey tint',
    description_zh: '柔和的紫灰色调',
    description_vi: 'Ánh tím khói nhẹ nhàng',
    description_th: 'โทนสีเทาม่วงนุ่มนวล',
    prompt: 'change the hairstyle to a straight bob cut, soft lavender grey color',
    gender: Gender.FEMALE,
    length: HairLength.SHORT,
    color: HairColor.SILVER
  },

  // --- MALE STYLES (30) ---

  // Short
  {
    id: 'm1',
    name: 'High Fade Crew',
    name_zh: '高渐变圆寸',
    name_vi: 'Tóc Crew Cut Fade Cao',
    name_th: 'ทรงครูว์คัทไถสูง',
    description: 'Clean high fade with short top',
    description_zh: '清爽的高渐变铲青，顶部留短',
    description_vi: 'Cạo sát hai bên với phần đỉnh ngắn',
    description_th: 'ไถข้างไล่ระดับสูงพร้อมผมด้านบนสั้น',
    prompt: 'change the hairstyle to a high skin fade with a short crew cut top, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'm2',
    name: 'Textured Crop',
    name_zh: '纹理短盖头',
    name_vi: 'Tóc Crop Có Kết Cấu',
    name_th: 'ทรงครอปมีเท็กซ์เจอร์',
    description: 'French crop with texture',
    description_zh: '带有纹理感的法式短盖头',
    description_vi: 'Kiểu French crop được tỉa texture',
    description_th: 'ทรงเฟรนช์ครอปเซ็ตแบบมีมิติ',
    prompt: 'change the hairstyle to a textured French crop, dark brown hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BROWN
  },
  {
    id: 'm3',
    name: 'Blonde Buzz Cut',
    name_zh: '金发寸头',
    name_vi: 'Đầu Đinh Màu Vàng',
    name_th: 'ทรงสกินเฮดสีบลอนด์',
    description: 'Uniform short length',
    description_zh: '长度统一的寸头',
    description_vi: 'Độ dài ngắn đồng nhất',
    description_th: 'ผมสั้นเกรียนเสมอกัน',
    prompt: 'change the hairstyle to a uniform buzz cut, bleached blonde hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLONDE
  },
  {
    id: 'm4',
    name: 'Silver Caesar',
    name_zh: '银色凯撒头',
    name_vi: 'Tóc Caesar Màu Bạc',
    name_th: 'ทรงซีซาร์สีเงิน',
    description: 'Classic Caesar cut',
    description_zh: '经典的凯撒式短发，平刘海',
    description_vi: 'Kiểu tóc Caesar cổ điển',
    description_th: 'ทรงซีซาร์คลาสสิกพร้อมหน้าม้าตรง',
    prompt: 'change the hairstyle to a classic Caesar cut with straight bangs, silver grey hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.SILVER
  },
  {
    id: 'm5',
    name: 'Red Faux Hawk',
    name_zh: '红色仿莫霍克',
    name_vi: 'Tóc Faux Hawk Màu Đỏ',
    name_th: 'ทรงฟอว์ฮอว์กสีแดง',
    description: 'Short sides, spiked center',
    description_zh: '两侧短，中间竖起',
    description_vi: 'Hai bên ngắn, phần giữa vuốt dựng',
    description_th: 'ข้างสั้น กลางตั้งแหลม',
    prompt: 'change the hairstyle to a short wide faux hawk, auburn red hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.RED
  },

  // Medium
  {
    id: 'm6',
    name: 'Classic Pompadour',
    name_zh: '经典庞巴度',
    name_vi: 'Tóc Pompadour Cổ Điển',
    name_th: 'ทรงปอมปาดัวร์คลาสสิก',
    description: 'Voluminous swept back',
    description_zh: '蓬松向后梳的大背头',
    description_vi: 'Vuốt ngược ra sau bồng bềnh',
    description_th: 'ผมเสยไปด้านหลังแบบมีวอลลุ่ม',
    prompt: 'change the hairstyle to a classic high-volume pompadour, shiny black hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'm7',
    name: 'Messy Quiff',
    name_zh: '凌乱飞机头',
    name_vi: 'Tóc Quiff Đánh Rối',
    name_th: 'ทรงควิฟฟ์แบบเซอร์ๆ',
    description: 'Casual upward sweep',
    description_zh: '随性向上梳理',
    description_vi: 'Vuốt lên tự nhiên',
    description_th: 'เสยขึ้นแบบลำลอง',
    prompt: 'change the hairstyle to a messy, textured quiff, medium brown hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'm8',
    name: 'Surfer Curtains',
    name_zh: '冲浪者中分',
    name_vi: 'Tóc Mái Quyển Vở Lãng Tử',
    name_th: 'ทรงแสกกลางสไตล์เซิร์ฟ',
    description: 'Middle part flow',
    description_zh: '中分流动感发型',
    description_vi: 'Rẽ ngôi giữa bồng bềnh',
    description_th: 'ผมแสกกลางพลิ้วไหว',
    prompt: 'change the hairstyle to 90s style curtain bangs, middle part, dirty blonde hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLONDE
  },
  {
    id: 'm9',
    name: 'Slick Back',
    name_zh: '油头后梳',
    name_vi: 'Tóc Vuốt Ngược Slick Back',
    name_th: 'ทรงสลิคแบ็ค',
    description: 'Smooth combed back',
    description_zh: '光滑向后梳理',
    description_vi: 'Chải ngược ra sau mượt mà',
    description_th: 'หวีเรียบไปด้านหลัง',
    prompt: 'change the hairstyle to a professional slicked back look, salt and pepper silver hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.SILVER
  },
  {
    id: 'm10',
    name: 'Green Mohawk',
    name_zh: '绿色莫霍克',
    name_vi: 'Tóc Mohawk Xanh Lá',
    name_th: 'ทรงโมฮอว์กสีเขียว',
    description: 'Punk style spiked',
    description_zh: '朋克风格竖发',
    description_vi: 'Vuốt dựng phong cách Punk',
    description_th: 'ทรงตั้งแหลมสไตล์พังก์',
    prompt: 'change the hairstyle to a punk rock mohawk, neon green hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.COLOR
  },

  // Long
  {
    id: 'm11',
    name: 'Man Bun Undercut',
    name_zh: '男士丸子头铲青',
    name_vi: 'Tóc Búi Man Bun Undercut',
    name_th: 'ทรงแมนบันไถข้าง',
    description: 'Top knot with shaved sides',
    description_zh: '顶部丸子头，两侧铲青',
    description_vi: 'Búi củ tỏi với hai bên cạo sát',
    description_th: 'มัดจุกด้านบนพร้อมไถข้าง',
    prompt: 'change the hairstyle to a man bun with a sharp undercut, black hair',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BLACK
  },
  {
    id: 'm12',
    name: 'Shoulder Flow',
    name_zh: '齐肩中长发',
    name_vi: 'Tóc Dài Ngang Vai Lãng Tử',
    name_th: 'ผมยาวประบ่าธรรมชาติ',
    description: 'Natural wavy flow',
    description_zh: '自然微卷的流动感',
    description_vi: 'Sóng tóc tự nhiên',
    description_th: 'ผมลอนคลื่นธรรมชาติ',
    prompt: 'change the hairstyle to shoulder-length natural wavy flow, dark brown hair',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BROWN
  },
  {
    id: 'm13',
    name: 'Viking Braids',
    name_zh: '维京编发',
    name_vi: 'Tóc Tết Kiểu Viking',
    name_th: 'ผมถักเปียสไตล์ไวกิ้ง',
    description: 'Half-up braided style',
    description_zh: '半扎发编织风格',
    description_vi: 'Kiểu tết tóc nửa đầu',
    description_th: 'ทรงถักเปียครึ่งหัว',
    prompt: 'change the hairstyle to a Viking style half-up braid, blonde hair',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BLONDE
  },
  {
    id: 'm14',
    name: 'Long Rocker Layers',
    name_zh: '摇滚长碎发',
    name_vi: 'Tóc Dài Tỉa Layer Rocker',
    name_th: 'ผมยาวสไลด์สไตล์ร็อคเกอร์',
    description: '70s rock style',
    description_zh: '70年代摇滚风格',
    description_vi: 'Phong cách rock thập niên 70',
    description_th: 'สไตล์ร็อคยุค 70',
    prompt: 'change the hairstyle to long 70s rock star layered hair, reddish brown hair',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.RED
  },
  {
    id: 'm15',
    name: 'Dreadlocks',
    name_zh: '脏辫',
    name_vi: 'Tóc Dreadlocks',
    name_th: 'ทรงเดรดร็อก',
    description: 'Long locs',
    description_zh: '长款脏辫',
    description_vi: 'Tóc bện thừng dài',
    description_th: 'ผมถักเดรดร็อกยาว',
    prompt: 'change the hairstyle to long dreadlocks tied back, black hair',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BLACK
  },
  {
    id: 'm16',
    name: 'Two Block Cut',
    name_zh: '韩式二分区',
    name_vi: 'Tóc Two Block Hàn Quốc',
    name_th: 'ทรงทูบล็อก (Two Block)',
    description: 'Shaved sides, long top',
    description_zh: '两侧推短，头顶留长',
    description_vi: 'Cạo sát hai bên, phần đỉnh để dài',
    description_th: 'ไถข้าง ด้านบนยาวปิดลงมา',
    prompt: 'change the hairstyle to a Korean style Two Block cut, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'm17',
    name: 'Military Flat Top',
    name_zh: '平头/方头',
    name_vi: 'Đầu Bằng Quân Đội',
    name_th: 'ทรงลานบิน (Flat Top)',
    description: 'Boxy shape top',
    description_zh: '顶部平整方正',
    description_vi: 'Phần đỉnh cắt bằng phẳng',
    description_th: 'ด้านบนตัดเรียบแบนเป็นระนาบ',
    prompt: 'change the hairstyle to a military flat top haircut, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'm18',
    name: 'Modern Bowl Cut',
    name_zh: '现代锅盖头',
    name_vi: 'Đầu Nấm Hiện Đại',
    name_th: 'ทรงกะลาครอบโมเดิร์น',
    description: 'Straight fringe all around',
    description_zh: '整齐的圆形刘海',
    description_vi: 'Mái ngố cắt tròn quanh đầu',
    description_th: 'หน้าม้าตัดตรงรอบศีรษะแบบทันสมัย',
    prompt: 'change the hairstyle to a modern texture bowl cut, ash brown hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'm19',
    name: 'Modern Mullet',
    name_zh: '男士狼尾',
    name_vi: 'Tóc Mullet Nam',
    name_th: 'ทรงมัลเล็ตชาย',
    description: 'Business front, party back',
    description_zh: '前短后长的潮流发型',
    description_vi: 'Phía trước ngắn, phía sau dài',
    description_th: 'ข้างหน้าสั้น ข้างหลังยาว',
    prompt: 'change the hairstyle to a stylish modern mullet, black hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'm20',
    name: 'Male Afro',
    name_zh: '男士爆炸头',
    name_vi: 'Tóc Xù Nam',
    name_th: 'ทรงแอฟโฟรชาย',
    description: 'Rounded natural curls',
    description_zh: '圆形自然卷',
    description_vi: 'Tóc xoăn xù tự nhiên tròn',
    description_th: 'ผมหยิกฟูทรงกลม',
    prompt: 'change the hairstyle to a medium sized afro, black hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BLACK
  },
  {
    id: 'm21',
    name: 'Cornrows Male',
    name_zh: '男士贴头辫',
    name_vi: 'Tóc Tết Châu Phi Nam',
    name_th: 'ทรงถักเปียติดหนังหัวชาย',
    description: 'Straight back braids',
    description_zh: '向后编织的贴头辫',
    description_vi: 'Tết tóc thẳng ra sau',
    description_th: 'ถักเปียยาวตรงไปด้านหลัง',
    prompt: 'change the hairstyle to straight back cornrows, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'm22',
    name: 'Spiky Texture',
    name_zh: '刺猬头',
    name_vi: 'Tóc Vuốt Nhọn',
    name_th: 'ทรงผมตั้งหนาม (Spiky)',
    description: 'Short spiky messy look',
    description_zh: '短发凌乱竖起',
    description_vi: 'Tóc ngắn vuốt dựng lộn xộn',
    description_th: 'ผมสั้นเซ็ตตั้งแบบยุ่งๆ',
    prompt: 'change the hairstyle to short spiky textured hair, blonde tips',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLONDE
  },
  {
    id: 'm23',
    name: 'Classic Side Part',
    name_zh: '经典绅士侧分',
    name_vi: 'Rẽ Ngôi Lệch Cổ Điển',
    name_th: 'ทรงแสกข้างคลาสสิก',
    description: 'Formal business style',
    description_zh: '正式商务风格',
    description_vi: 'Phong cách doanh nhân lịch lãm',
    description_th: 'สไตล์นักธุรกิจเรียบหรู',
    prompt: 'change the hairstyle to a classic gentleman side part, dark brown hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'm24',
    name: 'Korean Wavy Perm',
    name_zh: '韩式纹理烫',
    name_vi: 'Uốn Xoăn Nhẹ Hàn Quốc',
    name_th: 'ดัดลอนเกาหลี (Wavy Perm)',
    description: 'Soft curls with bangs',
    description_zh: '带刘海的柔和卷发',
    description_vi: 'Xoăn nhẹ có mái',
    description_th: 'ดัดลอนคลายพร้อมหน้าม้า',
    prompt: 'change the hairstyle to a Korean style soft wavy perm with bangs, brown hair',
    gender: Gender.MALE,
    length: HairLength.MEDIUM,
    color: HairColor.BROWN
  },
  {
    id: 'm25',
    name: 'Bleached Tips',
    name_zh: '发尾挑染',
    name_vi: 'Nhuộm Đuôi Tóc',
    name_th: 'ย้อมปลายผม (Frosted Tips)',
    description: 'Dark roots, light ends',
    description_zh: '深色发根，浅色发尾',
    description_vi: 'Chân tóc đen, đuôi tóc sáng',
    description_th: 'โคนผมดำ ปลายผมสว่าง',
    prompt: 'change the hairstyle to short spiky hair with frosted bleached tips',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.COLOR
  },
  {
    id: 'm26',
    name: 'Half Man Bun',
    name_zh: '半扎武士头',
    name_vi: 'Tóc Samurai Nửa Đầu',
    name_th: 'มัดจุกครึ่งหัว (Samurai)',
    description: 'Long hair half tied up',
    description_zh: '长发半扎',
    description_vi: 'Tóc dài buộc nửa đầu',
    description_th: 'ผมยาวมัดรวบครึ่งศีรษะ',
    prompt: 'change the hairstyle to a samurai style half man bun, long flowing hair at back, black',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BLACK
  },
  {
    id: 'm27',
    name: 'Ivy League',
    name_zh: '常春藤头',
    name_vi: 'Kiểu Tóc Ivy League',
    name_th: 'ทรงไอวี่ลีก',
    description: 'Smart short clean cut',
    description_zh: '干练整洁的短发',
    description_vi: 'Cắt ngắn gọn gàng, tri thức',
    description_th: 'ผมสั้นเรียบร้อยดูดีมีชาติตระกูล',
    prompt: 'change the hairstyle to a smart Ivy League haircut, blonde hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLONDE
  },
  {
    id: 'm28',
    name: 'Shaved Design',
    name_zh: '雕刻寸头',
    name_vi: 'Tóc Cạo Tạo Hình',
    name_th: 'แกะลายผม (Hair Tattoo)',
    description: 'Buzz cut with lines',
    description_zh: '带线条图案的寸头',
    description_vi: 'Đầu đinh có đường kẻ hoa văn',
    description_th: 'สกินเฮดพร้อมแกะลายกราฟิก',
    prompt: 'change the hairstyle to a buzz cut with a shaved line design on the side, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
  {
    id: 'm29',
    name: 'Long Surfer Hair',
    name_zh: '冲浪长发',
    name_vi: 'Tóc Dài Lướt Sóng',
    name_th: 'ผมยาวเซอร์เฟอร์',
    description: 'Sun-bleached long messy',
    description_zh: '阳光漂白的凌乱长发',
    description_vi: 'Tóc dài rối màu nắng',
    description_th: 'ผมยาวสีกัดแดดแบบธรรมชาติ',
    prompt: 'change the hairstyle to long messy sun-bleached surfer hair, blonde',
    gender: Gender.MALE,
    length: HairLength.LONG,
    color: HairColor.BLONDE
  },
  {
    id: 'm30',
    name: 'Hard Part Fade',
    name_zh: '刻痕分界渐变',
    name_vi: 'Fade Rẽ Ngôi Cạo',
    name_th: 'ไถข้างแสกกลางชัด (Hard Part)',
    description: 'Fade with shaved part line',
    description_zh: '带刻痕分界线的渐变',
    description_vi: 'Fade với đường rẽ ngôi được cạo rõ',
    description_th: 'ไถไล่ระดับพร้อมกรีดรอยแสกชัดเจน',
    prompt: 'change the hairstyle to a fade with a distinct shaved hard part line, black hair',
    gender: Gender.MALE,
    length: HairLength.SHORT,
    color: HairColor.BLACK
  },
];